/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsRestaurantIdIndexRouteImport } from './routes/restaurants.$restaurantId.index'
import { Route as RestaurantsRestaurantIdMenusMenuIdRouteImport } from './routes/restaurants.$restaurantId.menus.$menuId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRestaurantIdIndexRoute =
  RestaurantsRestaurantIdIndexRouteImport.update({
    id: '/restaurants/$restaurantId/',
    path: '/restaurants/$restaurantId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantsRestaurantIdMenusMenuIdRoute =
  RestaurantsRestaurantIdMenusMenuIdRouteImport.update({
    id: '/restaurants/$restaurantId/menus/$menuId',
    path: '/restaurants/$restaurantId/menus/$menuId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/restaurants/$restaurantId/': typeof RestaurantsRestaurantIdIndexRoute
  '/restaurants/$restaurantId/menus/$menuId': typeof RestaurantsRestaurantIdMenusMenuIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/restaurants/$restaurantId': typeof RestaurantsRestaurantIdIndexRoute
  '/restaurants/$restaurantId/menus/$menuId': typeof RestaurantsRestaurantIdMenusMenuIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/restaurants/$restaurantId/': typeof RestaurantsRestaurantIdIndexRoute
  '/restaurants/$restaurantId/menus/$menuId': typeof RestaurantsRestaurantIdMenusMenuIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/restaurants/$restaurantId/'
    | '/restaurants/$restaurantId/menus/$menuId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/restaurants/$restaurantId'
    | '/restaurants/$restaurantId/menus/$menuId'
  id:
    | '__root__'
    | '/'
    | '/restaurants/$restaurantId/'
    | '/restaurants/$restaurantId/menus/$menuId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RestaurantsRestaurantIdIndexRoute: typeof RestaurantsRestaurantIdIndexRoute
  RestaurantsRestaurantIdMenusMenuIdRoute: typeof RestaurantsRestaurantIdMenusMenuIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$restaurantId/': {
      id: '/restaurants/$restaurantId/'
      path: '/restaurants/$restaurantId'
      fullPath: '/restaurants/$restaurantId/'
      preLoaderRoute: typeof RestaurantsRestaurantIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$restaurantId/menus/$menuId': {
      id: '/restaurants/$restaurantId/menus/$menuId'
      path: '/restaurants/$restaurantId/menus/$menuId'
      fullPath: '/restaurants/$restaurantId/menus/$menuId'
      preLoaderRoute: typeof RestaurantsRestaurantIdMenusMenuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RestaurantsRestaurantIdIndexRoute: RestaurantsRestaurantIdIndexRoute,
  RestaurantsRestaurantIdMenusMenuIdRoute:
    RestaurantsRestaurantIdMenusMenuIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
